// ADMIN -> LANDING for the site_settings (Hero) and Galería fields, rendered by the real landing page in a browser.
// The rows are shaped exactly like the Admin saves them: English written by the admin (`.en`, `alt_en`) and the
// Spanish generated by DeepL (`.es`, `alt_es`). English visitors must see the original, Spanish visitors the translation.
// Everything is mocked (admin-test.supabase.co); no real project and no DeepL.
import assert from 'node:assert/strict';
import test from 'node:test';
import { chromium, expect } from '@playwright/test';

const base = process.env.ADMIN_TEST_BASE_URL ?? 'http://localhost:5174';

const heroRows = [
  { key: 'home.hero.title.en', value: 'Experience the Pacific' },
  { key: 'home.hero.title.es', value: 'Vive el Pacífico' },
  { key: 'home.hero.eyebrow.en', value: 'Private charters in Costa Rica' },
  { key: 'home.hero.eyebrow.es', value: 'Chárters privados en Costa Rica' },
  { key: 'home.hero.subtitle.en', value: 'Fishing, sunsets and unforgettable memories.' },
  { key: 'home.hero.subtitle.es', value: 'Pesca, atardeceres y recuerdos inolvidables.' },
  { key: 'home.hero.image_alt.en', value: 'Private boat at sunrise' },
  { key: 'home.hero.image_alt.es', value: 'Bote privado al amanecer' },
].map((row) => ({ ...row, type: 'text', active: true }));

const aboutRows = [
  ['about.title', 'Local passion on the Pacific coast', 'Pasión local en la costa del Pacífico'],
  ['about.description', 'Family-run private charters since 2015.', 'Chárters privados familiares desde 2015.'],
  ['about.preview_text', 'We take you fishing at dawn.\n\nThen we anchor for lunch.', 'Te llevamos a pescar al amanecer.\n\nLuego anclamos para almorzar.'],
  ['about.image_alt', 'Crew with a fresh catch', 'Tripulación con pesca fresca'],
].flatMap(([base, en, es]) => [{ key: `${base}.en`, value: en, type: 'text', active: true }, { key: `${base}.es`, value: es, type: 'text', active: true }]);

const galleryRows = [
  { id: 'gal-1', src: '/images/papagayo-logo.png', image_url: '/images/papagayo-logo.png', alt: 'Boat at dock', alt_en: 'Boat at dock', alt_es: 'Bote en el muelle', category: 'boats', active: true, sort_order: 1 },
];

async function landing(language) {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1366, height: 1200 } });
  await page.addInitScript((value) => window.localStorage.setItem('language', value), language);
  await page.route('https://admin-test.supabase.co/**', async (route) => {
    const request = route.request();
    const url = new URL(request.url());
    const path = url.pathname;
    const empty = { json: [], headers: { 'access-control-expose-headers': 'content-range', 'content-range': '0-0/0' } };
    if (request.method() !== 'GET') return route.fulfill({ json: [] });
    if (path.endsWith('/site_settings')) {
      const wanted = url.searchParams.get('key') ?? '';
      const keys = wanted.startsWith('in.(') ? wanted.slice(4, -1).split(',').map((key) => key.replace(/^"|"$/g, '')) : null;
      return route.fulfill({ json: [...heroRows, ...aboutRows].filter((row) => !keys || keys.includes(row.key)) });
    }
    if (path.endsWith('/gallery_images')) return route.fulfill({ json: galleryRows });
    return route.fulfill(empty);
  });
  await page.goto(`${base}/`);
  const accept = page.getByRole('dialog').getByRole('button', { name: /Aceptar|Accept/i });
  if (await accept.isVisible().catch(() => false)) await accept.click();
  return { browser, page };
}

test('LANDING EN: the hero shows exactly what the admin wrote in English', async () => {
  const { browser, page } = await landing('en');
  try {
    await expect(page.locator('h1')).toHaveText(/Experience\s*the Pacific/, { timeout: 15000 });
    await expect(page.getByText('Private charters in Costa Rica').first()).toBeVisible();
    await expect(page.getByText('Fishing, sunsets and unforgettable memories.').first()).toBeVisible();
    await expect(page.locator('img[alt="Private boat at sunrise"]').first()).toBeAttached();
    assert.equal(await page.getByText('Vive el Pacífico').count(), 0);
  } finally { await browser.close(); }
});

test('LANDING ES: the hero shows the DeepL translation generated when the admin saved', async () => {
  const { browser, page } = await landing('es');
  try {
    await expect(page.locator('h1')).toHaveText(/Vive\s*el Pacífico/, { timeout: 15000 });
    await expect(page.getByText('Chárters privados en Costa Rica').first()).toBeVisible();
    await expect(page.getByText('Pesca, atardeceres y recuerdos inolvidables.').first()).toBeVisible();
    await expect(page.locator('img[alt="Bote privado al amanecer"]').first()).toBeAttached();
    assert.equal(await page.getByText('Experience the Pacific').count(), 0);
  } finally { await browser.close(); }
});

test('LANDING gallery alt text: EN visitors get alt_en, ES visitors get the translated alt_es', async () => {
  for (const [language, expected] of [['en', 'Boat at dock'], ['es', 'Bote en el muelle']]) {
    const { browser, page } = await landing(language);
    try {
      await expect(page.locator(`img[alt="${expected}"]`).first()).toBeAttached({ timeout: 15000 });
    } finally { await browser.close(); }
  }
});

test('LANDING About (EN / ES): title, description, preview paragraphs and image alt show the original English or the DeepL Spanish', async () => {
  const cases = [
    ['en', 'Local passion on the Pacific coast', 'Family-run private charters since 2015.', ['We take you fishing at dawn.', 'Then we anchor for lunch.'], 'Crew with a fresh catch', 'Pasión local en la costa del Pacífico'],
    ['es', 'Pasión local en la costa del Pacífico', 'Chárters privados familiares desde 2015.', ['Te llevamos a pescar al amanecer.', 'Luego anclamos para almorzar.'], 'Tripulación con pesca fresca', 'Local passion on the Pacific coast'],
  ];
  for (const [language, title, description, paragraphs, alt, otherTitle] of cases) {
    const { browser, page } = await landing(language);
    try {
      await expect(page.getByText(title, { exact: true }).first()).toBeAttached({ timeout: 20000 });
      await expect(page.getByText(description, { exact: true }).first()).toBeAttached();
      for (const paragraph of paragraphs) await expect(page.getByText(paragraph, { exact: true }).first()).toBeAttached();
      await expect(page.locator(`img[alt="${alt}"]`).first()).toBeAttached();
      assert.equal(await page.getByText(otherTitle, { exact: true }).count(), 0, 'the other language must not be rendered');
    } finally { await browser.close(); }
  }
});
