// PUBLIC BOATS (Fleet section of the real landing page), rendered in a browser, EN / ES, desktop / mobile.
// Rows are shaped exactly like the Admin saves them: English written by the admin (`badge_en`, `label_en`) and the
// Spanish generated by DeepL (`badge_es`, `label_es`). The legacy columns hold a distinctive value so the test can
// prove they are never shown. The boat name is a proper name and must stay identical in both languages.
// Everything is mocked (admin-test.supabase.co); no real project, no DeepL, nothing is written.
import assert from 'node:assert/strict';
import test from 'node:test';
import { chromium, expect } from '@playwright/test';

const base = process.env.ADMIN_TEST_BASE_URL ?? 'http://localhost:5174';

const boat = {
  id: 'boat-1', slug: 'second-wind', name: 'Second Wind', image_url: null, images: null, length: '32 ft', engine: 'Yamaha 250', max_guests: 10,
  featured_spec: null, active: true, sort_order: 1,
  badge: 'LEGACY-BADGE', badge_en: 'Luxury meets nature', badge_es: 'Lujo y naturaleza',
};
const equipment = [
  { id: 'e1', boat_id: 'boat-1', label: 'LEGACY-ONE', label_en: 'Garmin GPS', label_es: 'GPS Garmin', sort_order: 1, active: true },
  { id: 'e2', boat_id: 'boat-1', label: 'LEGACY-TWO', label_en: 'Live bait well', label_es: 'Tanque de cebo vivo', sort_order: 2, active: true },
  { id: 'e3', boat_id: 'boat-1', label: 'LEGACY-THREE', label_en: 'Safety equipment and life jackets for every guest on board', label_es: 'Equipo de seguridad y chalecos salvavidas para cada huésped a bordo', sort_order: 3, active: true },
];
const tourPackage = {
  id: 'pkg-1', active: true, name: 'Half Day', package_type: 'half-day', departure_times: null, meal_options: null, description: 'Half day', package_included: null,
  duration_minutes: 240, sort_order: 1, base_price: 900, included_guests: 4, max_guests: 10, extra_guest_price: 50, custom_quote: false,
  boat_tours: { id: 'link-1', boat_id: 'boat-1', tour_id: 'tour-1', active: true, boats: { active: true, max_guests: 10 }, tours: { id: 'tour-1', title: 'Fishing', category: 'Fishing', description: 'Half day fishing', image_url: null, included: null, highlights: null, active: true } },
};

const expected = {
  en: { badge: 'Luxury meets nature', items: ['Garmin GPS', 'Live bait well', 'Safety equipment and life jackets for every guest on board'], other: ['Lujo y naturaleza', 'GPS Garmin', 'Tanque de cebo vivo', 'Equipo de seguridad'], explore: 'Explore boat Second Wind' },
  es: { badge: 'Lujo y naturaleza', items: ['GPS Garmin', 'Tanque de cebo vivo', 'Equipo de seguridad y chalecos salvavidas para cada huésped a bordo'], other: ['Luxury meets nature', 'Garmin GPS', 'Live bait well', 'Safety equipment'], explore: 'Ver barco Second Wind' },
};
const viewports = { desktop: { width: 1366, height: 900 }, mobile: { width: 390, height: 844 } };

async function fleet(language, viewport) {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const page = await browser.newPage({ viewport });
  await page.addInitScript((value) => window.localStorage.setItem('language', value), language);
  await page.route('https://admin-test.supabase.co/**', async (route) => {
    const request = route.request();
    const path = new URL(request.url()).pathname;
    const empty = { json: [], headers: { 'access-control-expose-headers': 'content-range', 'content-range': '0-0/0' } };
    if (request.method() !== 'GET') return route.fulfill({ json: [] });
    if (path.endsWith('/boats')) return route.fulfill({ json: [boat] });
    if (path.endsWith('/boat_equipment')) return route.fulfill({ json: equipment });
    if (path.endsWith('/tour_packages')) return route.fulfill({ json: [tourPackage] });
    return route.fulfill(empty);
  });
  await page.goto(`${base}/`);
  const accept = page.getByRole('dialog').getByRole('button', { name: /Aceptar|Accept/i });
  if (await accept.isVisible().catch(() => false)) await accept.click();
  return { browser, page };
}

for (const [device, viewport] of Object.entries(viewports)) {
  for (const language of ['en', 'es']) {
    test(`PUBLIC BOATS ${device} ${language.toUpperCase()}: badge and equipment in ${language === 'en' ? 'English' : 'Spanish'}, boat name untranslated, no legacy value, no overflow`, async () => {
      const t = expected[language];
      const { browser, page } = await fleet(language, viewport);
      try {
        const region = page.getByRole('region', { name: /Barcos disponibles|Available boats/ });
        await expect(region.getByText('Second Wind').first()).toBeVisible({ timeout: 20000 });
        await region.getByRole('button', { name: t.explore, exact: true }).click();
        const dialog = page.getByRole('dialog').filter({ has: page.locator('#boat-detail-title') });
        await expect(dialog.locator('#boat-detail-title')).toHaveText('Second Wind'); // proper name, identical in EN and ES
        await expect(dialog.getByText(t.badge, { exact: true })).toBeVisible();
        for (const item of t.items) await expect(dialog.getByText(item, { exact: true })).toBeVisible();
        // the other language and the legacy columns never leak into the modal
        for (const text of [...t.other, 'LEGACY-BADGE', 'LEGACY-ONE', 'LEGACY-TWO', 'LEGACY-THREE']) assert.equal(await dialog.getByText(text).count(), 0, `"${text}" must not be visible in ${language}`);
        // and not anywhere else on the page either (card, teaser, booking panel)
        for (const text of ['LEGACY-BADGE', 'LEGACY-ONE']) assert.equal(await page.getByText(text).count(), 0);
        // translation length must not break the layout: no horizontal page overflow and every item stays inside the modal
        const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
        assert.equal(overflow, false, 'the page must not overflow horizontally');
        const modalBox = await dialog.boundingBox();
        for (const item of t.items) {
          const box = await dialog.getByText(item, { exact: true }).boundingBox();
          assert.ok(box.x >= modalBox.x - 1 && box.x + box.width <= modalBox.x + modalBox.width + 1, `"${item}" overflows the modal (${device})`);
        }
        await page.screenshot({ path: `tmp/translation-e2e/boats-${device}-${language}.png` });
      } finally { await browser.close(); }
    });
  }
}
