import { ChevronDown, ChevronRight, FileText, Globe2, Loader2, Monitor } from 'lucide-react';
import { useEffect, useMemo, useRef, useState } from 'react';

import { supabase } from '../../lib/supabase';
import type { StorageImage } from '../../services/imageService';
import { translateAllSiteContent, translateTextsToSpanish, type TranslateAllSiteContentResult } from '../../services/translationService';
import AdminConfirmDialog from './AdminConfirmDialog';
import AdminImageManager from './AdminImageManager';
import { AdminMediaAssetCard, AdminMediaAssetEditor } from './AdminMediaAssets';
import AdminVideoManager from './AdminVideoManager';

interface SiteSettingRow {
  key: string;
  value: string;
  type: string;
  active: boolean;
}

export interface ContentField {
  key: string;
  label: string;
  type: 'text' | 'textarea' | 'url' | 'boolean' | 'image' | 'video' | 'media_mode';
  fallback: string;
  aspect?: number;
  maxWidth?: number;
  maxHeight?: number;
}

export type Draft = Record<string, string>;

function storagePathFromPublicUrl(value?: string | null) {
  if (!value) return null;
  if (value.includes('/site-images/')) return value.split('/site-images/')[1] ?? null;
  try {
    const path = decodeURIComponent(new URL(value).pathname.replace(/^\//, ''));
    return /^(boats|tours|gallery|destinations|reviews|general)\/[A-Za-z0-9_-]+\/[A-Za-z0-9_-]+\.[a-z0-9]+$/.test(path) ? path : null;
  } catch {
    return null;
  }
}

// Portada (Hero) / About texts are stored as `<base>.en` and `<base>.es` in site_settings. The admin writes ONLY the
// English one; the Spanish `.es` key is generated by DeepL when the section is saved (and only for the English
// texts that changed) — it is not shown in the form.
const isDerivedSpanish = (field: ContentField) => field.key.endsWith('.es') && (field.type === 'text' || field.type === 'textarea');
const spanishKeyOf = (key: string) => (key.endsWith('.en') ? `${key.slice(0, -3)}.es` : null);

function defaultsFrom(fields: ContentField[]): Draft {
  return fields.reduce<Draft>((acc, field) => {
    acc[field.key] = field.fallback;
    return acc;
  }, {});
}

interface ContentSectionProps {
  title: string;
  description: string;
  fields: ContentField[];
  /** Success notice shown after saving the texts (defaults to "<title> actualizado."). */
  savedMessage?: string;
  imageRequireReplacement?: boolean;
  preview?: (draft: Draft) => React.ReactNode;
  /** Splits this section into "Media" / "Textos" inner tabs so it isn't one long scroll. Save stays unified (one section = one payload). */
  mediaTextTabs?: boolean;
}

export function ContentSection({ title, description, fields, savedMessage, imageRequireReplacement = false, preview, mediaTextTabs = false }: ContentSectionProps) {
  const keys = useMemo(() => fields.map((field) => field.key), [fields]);
  const [draft, setDraft] = useState<Draft>(() => defaultsFrom(fields));
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  // Values as last loaded/saved: only English texts that differ from them are translated on save.
  const loadedRef = useRef<Draft>({});
  const [showExtraSlides, setShowExtraSlides] = useState(false);
  const [heroMediaMode, setHeroMediaMode] = useState<'image' | 'video'>('image');
  const [switchingMediaMode, setSwitchingMediaMode] = useState(false);
  const [innerTab, setInnerTab] = useState<'media' | 'texts'>('media');
  // The asset (image / video) open in its editor; the list only shows summary cards.
  const [assetEditor, setAssetEditor] = useState<{ field: ContentField; kind: 'image' | 'video' } | null>(null);

  const imageFields = useMemo(() => fields.filter((field) => field.type === 'image'), [fields]);
  const primaryImageFields = useMemo(() => imageFields.filter((field) => !field.key.includes('.slide_') && field.key !== 'home.hero.video_poster'), [imageFields]);
  const extraImageFields = useMemo(() => imageFields.filter((field) => field.key.includes('.slide_')), [imageFields]);
  const videoFields = useMemo(() => fields.filter((field) => field.type === 'video'), [fields]);
  const videoPosterField = useMemo(() => fields.find((field) => field.key === 'home.hero.video_poster'), [fields]);
  const textFields = useMemo(
    () => fields.filter((field) => !['image', 'video', 'media_mode'].includes(field.type) && !isDerivedSpanish(field)),
    [fields],
  );

  // `silent` refreshes the values without swapping the whole form for the loading text (used after an upload/delete, so an open editor stays open).
  async function loadSettings(silent = false) {
    if (!silent) setLoading(true);
    setError('');
    const { data, error } = await supabase
      .from('site_settings')
      .select('key, value, type, active')
      .in('key', keys)
      .order('key');

    setLoading(false);
    if (error) {
      setError(error.message);
      setDraft(defaultsFrom(fields));
      return;
    }

    const rows = (data ?? []) as SiteSettingRow[];
    const nextDraft = defaultsFrom(fields);
    rows.forEach((row) => {
      if (row.key in nextDraft && row.value) nextDraft[row.key] = row.value;
    });
    setDraft(nextDraft);
    loadedRef.current = nextDraft;
    if (videoFields.length) setHeroMediaMode(nextDraft['home.hero.media_mode'] === 'video' ? 'video' : 'image');
  }

  useEffect(() => {
    void loadSettings();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  async function upsertKey(key: string, value: string, type: string) {
    const { error } = await supabase.from('site_settings').upsert({
      key,
      value,
      type,
      active: true,
      updated_at: new Date().toISOString(),
    });
    if (error) throw new Error(error.message);
  }

  async function saveSettings() {
    setSaving(true);
    setError('');
    setNotice('');
    try {
      // 1) Work out what to write and which English texts changed (cleared ones fall back to the code defaults).
      const writes: Array<{ key: string; value: string; type: string; spanishKey: string | null; changed: boolean; cleared: boolean }> = [];
      for (const field of fields) {
        if (field.type === 'image' || field.type === 'video' || isDerivedSpanish(field)) continue; // images/videos: their own managers; .es: generated
        const raw = draft[field.key];
        const typed = (raw ?? '').trim();
        const value = field.type === 'boolean' ? (raw !== 'false' ? 'true' : 'false') : (typed || field.fallback);
        const spanishKey = field.type === 'text' || field.type === 'textarea' ? spanishKeyOf(field.key) : null;
        writes.push({ key: field.key, value, type: field.type, spanishKey, cleared: Boolean(spanishKey) && !typed, changed: Boolean(spanishKey) && Boolean(typed) && value !== (loadedRef.current[field.key] ?? '') });
      }
      // 2) English -> Spanish for everything that changed, in one request, BEFORE any write: if DeepL fails
      //    nothing is saved and the form keeps what was typed.
      const spanish = await translateTextsToSpanish(writes.filter((write) => write.changed).map((write) => write.value));
      // 3) Persist EN (as before) and, for changed texts, the generated ES; unchanged texts leave their ES alone.
      for (const write of writes) {
        await upsertKey(write.key, write.value, write.type);
        if (!write.spanishKey) continue;
        if (write.changed) await upsertKey(write.spanishKey, spanish.get(write.value) ?? '', write.type);
        else if (write.cleared) await upsertKey(write.spanishKey, fields.find((field) => field.key === write.spanishKey)?.fallback ?? '', write.type);
      }
      setNotice(`${savedMessage ?? `${title} actualizado.`} La pagina publica usara estos valores sin redesplegar.`);
      await loadSettings();
    } catch (saveError) {
      setError(saveError instanceof Error ? saveError.message : 'No se pudo guardar el contenido.');
    } finally {
      setSaving(false);
    }
  }

  async function handleImageSaved(field: ContentField, image: StorageImage) {
    try {
      await upsertKey(field.key, image.public_url, 'image');
      setNotice('Imagen actualizada.');
      await loadSettings(true);
    } catch (imageError) {
      throw new Error(imageError instanceof Error ? imageError.message : 'No se pudo guardar la imagen.');
    }
  }

  async function ensureImageSetting(field: ContentField) {
    const { error } = await supabase.from('site_settings').upsert({
      key: field.key, value: draft[field.key] ?? field.fallback, type: 'image', active: true,
    }, { onConflict: 'key', ignoreDuplicates: true });
    if (error) throw new Error(error.message);
  }

  async function handleImageDeleted(field: ContentField, storagePath: string) {
    try {
      await upsertKey(field.key, field.fallback, 'image');
      setNotice('Imagen eliminada. El sitio vuelve al contenido por defecto.');
      await loadSettings(true);
    } catch {
      setNotice(`No se pudo actualizar la referencia de la imagen eliminada: ${storagePath}`);
    }
  }

  async function handleVideoSaved(field: ContentField, video: StorageImage) {
    try {
      await upsertKey(field.key, video.public_url, 'video');
      setNotice('Video actualizado.');
      await loadSettings(true);
    } catch (videoError) {
      throw new Error(videoError instanceof Error ? videoError.message : 'No se pudo guardar el video.');
    }
  }

  async function handleVideoDeleted(field: ContentField, storagePath: string) {
    try {
      await upsertKey(field.key, field.fallback, 'video');
      setNotice('Video eliminado. El sitio vuelve al contenido por defecto.');
      await loadSettings(true);
    } catch {
      setNotice(`No se pudo actualizar la referencia del video eliminado: ${storagePath}`);
    }
  }

  function updateDraft(key: string, value: string) {
    setDraft((current) => ({ ...current, [key]: value }));
  }

  async function switchHeroMediaMode(mode: 'image' | 'video') {
    if (mode === heroMediaMode) return;
    setSwitchingMediaMode(true);
    try {
      await upsertKey('home.hero.media_mode', mode, 'media_mode');
      setDraft((current) => ({ ...current, 'home.hero.media_mode': mode }));
      setHeroMediaMode(mode);
      setNotice(`Modo de la Portada cambiado a ${mode === 'video' ? 'video' : 'imagenes'}. Los videos guardados se conservaron.`);
    } catch (switchError) {
      setError(switchError instanceof Error ? switchError.message : 'No se pudo cambiar el modo de la Portada.');
    } finally {
      setSwitchingMediaMode(false);
    }
  }

  // The managers below are the same ones the inline lists used (replace / delete / R2 URL, same props); they now live in the asset editor.
  function renderImageManager(field: ContentField) {
    const isPoster = field.key === 'home.hero.video_poster';
    const isPrimary = primaryImageFields.includes(field);
    return (
      <AdminImageManager
        resourceTable="site_settings"
        resourceId={field.key}
        folder="general"
        currentImageUrl={draft[field.key]}
        currentStoragePath={storagePathFromPublicUrl(draft[field.key])}
        label={isPoster ? field.label : draft[`${field.key.replace(/\.mobile_image$/, '').replace(/\.image$/, '')}.image_alt.en`] ?? field.label}
        aspect={field.aspect ?? 16 / 9}
        maxWidth={field.maxWidth ?? 1920}
        maxHeight={field.maxHeight ?? 1080}
        maxSizeMB={0.9}
        {...(isPrimary ? { beforeUpload: () => ensureImageSetting(field) } : {})}
        {...(isPoster ? {} : { requireReplacementToDelete: imageRequireReplacement && Boolean(field.fallback) })}
        onImageSaved={(image) => handleImageSaved(field, image)}
        onImageDeleted={(storagePath) => handleImageDeleted(field, storagePath)}
      />
    );
  }

  function renderVideoManager(field: ContentField) {
    return (
      <AdminVideoManager
        resourceTable="site_settings"
        resourceId={field.key}
        folder="general"
        currentVideoUrl={draft[field.key]}
        currentStoragePath={storagePathFromPublicUrl(draft[field.key])}
        label={field.label}
        onVideoSaved={(video) => handleVideoSaved(field, video)}
        onVideoDeleted={(storagePath) => handleVideoDeleted(field, storagePath)}
      />
    );
  }

  const assetCard = (field: ContentField, kind: 'image' | 'video') => (
    <AdminMediaAssetCard key={field.key} label={field.label} kind={kind} url={draft[field.key]} onEdit={() => setAssetEditor({ field, kind })} />
  );

  return (
    <section className="admin-card admin-content-section">
      <h2 className="admin-card__title"><FileText size={18} /> {title}</h2>
      <p className="admin-muted">{description}</p>
      {error ? <div className="admin-alert admin-alert--danger">{error}</div> : null}
      {notice ? <div className="admin-alert admin-alert--success">{notice}</div> : null}
      {loading ? (
        <p className="admin-muted">Cargando contenido...</p>
      ) : (
        <div className="grid gap-5">
          {mediaTextTabs ? (
            <nav className="admin-tabs" aria-label={`Secciones de ${title}`}>
              <button type="button" aria-pressed={innerTab === 'media'} className={`admin-tab${innerTab === 'media' ? ' admin-tab--active' : ''}`} onClick={() => setInnerTab('media')}>Media</button>
              <button type="button" aria-pressed={innerTab === 'texts'} className={`admin-tab${innerTab === 'texts' ? ' admin-tab--active' : ''}`} onClick={() => setInnerTab('texts')}>Textos</button>
            </nav>
          ) : null}

          <div style={mediaTextTabs && innerTab !== 'media' ? { display: 'none' } : undefined} className="grid gap-5">
          {videoFields.length > 0 ? (
            <div className="flex flex-wrap items-center justify-between gap-2">
              <p className="admin-muted font-extrabold">Fondo de la Portada</p>
              <div className="admin-segmented" role="group" aria-label="Tipo de fondo de la Portada">
                <button
                  type="button"
                  aria-pressed={heroMediaMode === 'image'}
                  className={heroMediaMode === 'image' ? 'admin-segmented__option--active' : ''}
                  disabled={switchingMediaMode}
                  onClick={() => void switchHeroMediaMode('image')}
                >
                  Imágenes
                </button>
                <button
                  type="button"
                  aria-pressed={heroMediaMode === 'video'}
                  className={heroMediaMode === 'video' ? 'admin-segmented__option--active' : ''}
                  disabled={switchingMediaMode}
                  onClick={() => void switchHeroMediaMode('video')}
                >
                  Video
                </button>
              </div>
            </div>
          ) : null}

          {(videoFields.length === 0 || heroMediaMode === 'image') && primaryImageFields.length > 0 ? (
            <div className="admin-media-grid">{primaryImageFields.map((field) => assetCard(field, 'image'))}</div>
          ) : null}

          {(videoFields.length === 0 || heroMediaMode === 'image') && extraImageFields.length > 0 ? (
            <div className="grid gap-3">
              <button
                className="admin-btn admin-btn--ghost"
                type="button"
                onClick={() => setShowExtraSlides((current) => !current)}
                style={{ justifySelf: 'start' }}
              >
                {showExtraSlides ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
                {showExtraSlides ? 'Ocultar diapositivas adicionales' : `Mostrar diapositivas adicionales (${extraImageFields.length})`}
              </button>
              {showExtraSlides ? <div className="admin-media-grid">{extraImageFields.map((field) => assetCard(field, 'image'))}</div> : null}
            </div>
          ) : null}

          {videoFields.length > 0 && heroMediaMode === 'video' ? (
            <div className="admin-media-grid">
              {videoFields.map((field) => assetCard(field, 'video'))}
              {videoPosterField ? assetCard(videoPosterField, 'image') : null}
            </div>
          ) : null}
          </div>

          <div style={mediaTextTabs && innerTab !== 'texts' ? { display: 'none' } : undefined} className="grid gap-5">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <p className="admin-muted font-extrabold">Textos</p>
          </div>

          <div className="grid gap-3 lg:grid-cols-2">
            {textFields.map((field) => (
              field.type === 'boolean' ? (
                <label className="flex items-center gap-2" key={field.key}>
                  <input
                    type="checkbox"
                    checked={draft[field.key] !== 'false'}
                    onChange={(event) => updateDraft(field.key, String(event.target.checked))}
                  />
                  <span className="admin-muted">{field.label}</span>
                </label>
              ) : (
                <label className={`grid gap-1${field.type === 'textarea' ? ' lg:col-span-2' : ''}`} key={field.key}>
                  <span className="admin-muted">{field.label.replace(/ EN$/, '')}</span>
                  {field.type === 'textarea' ? (
                    <textarea className="admin-input admin-content-textarea" rows={field.key.includes('.story') ? 9 : field.key.includes('preview_text') ? 6 : 4} value={draft[field.key]} onChange={(event) => updateDraft(field.key, event.target.value)} />
                  ) : (
                    <input className="admin-input" value={draft[field.key]} onChange={(event) => updateDraft(field.key, event.target.value)} />
                  )}
                </label>
              )
            ))}
          </div>

          {preview ? (
            <div className="admin-content-preview">
              <p className="admin-content-preview__label"><Monitor size={14} aria-hidden="true" /> Vista previa</p>
              {preview(draft)}
            </div>
          ) : null}
          </div>

          <div className="admin-image-manager__actions">
            <button className="admin-btn" type="button" disabled={saving} onClick={() => void saveSettings()}>
              {saving ? 'Guardando...' : 'Guardar'}
            </button>
            <button className="admin-btn admin-btn--ghost" type="button" onClick={() => void loadSettings()}>Cancelar</button>
          </div>
        </div>
      )}
      <AdminMediaAssetEditor open={Boolean(assetEditor)} title={assetEditor?.field.label ?? ''} onClose={() => setAssetEditor(null)}>
        {assetEditor ? (assetEditor.kind === 'video' ? renderVideoManager(assetEditor.field) : renderImageManager(assetEditor.field)) : null}
      </AdminMediaAssetEditor>
    </section>
  );
}

// The BACKFILL / repair tool (formerly "Traducir todo el sitio", now BACKFILL only): normal edits are translated on save. Covers tours, packages,
// inclusions, boats, gallery, payment methods, departure locations, Hero/
// About sections and reviews in one call — see translate-all-site-content.
// Site-wide maintenance tool, no longer shown on the content screens (normal edits are translated on save); kept here, unused by the UI, so a future backfill screen can reuse it.
export function TranslateAllSiteContentCard() {
  const [confirmOpen, setConfirmOpen] = useState(false);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState<TranslateAllSiteContentResult | null>(null);

  async function run() {
    setRunning(true);
    setError('');
    try {
      const response = await translateAllSiteContent();
      setResult(response);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'No se pudo completar la traducción del sitio.');
      setResult(null);
    } finally {
      setRunning(false);
      setConfirmOpen(false);
    }
  }

  return (
    <section className="admin-card">
      <h2 className="admin-card__title"><Globe2 size={18} /> Reparar traducciones antiguas</h2>
      <p className="admin-muted mb-4">
        Al guardar, cada texto que escribes en inglés ya se traduce al español automáticamente: no necesitas este botón
        para tus ediciones normales. Úsalo solo para completar contenido antiguo que todavía no tenga versión en español
        o inglés (tours, paquetes, inclusiones, botes, galería, métodos de pago, lugares de salida, estas secciones y
        comentarios). Las traducciones existentes nunca se sobrescriben.
      </p>

      <button className="admin-btn" type="button" disabled={running} onClick={() => setConfirmOpen(true)}>
        {running ? <Loader2 className="animate-spin" size={16} /> : <Globe2 size={16} />}
        {running ? 'Traduciendo contenido...' : 'Traducir contenido antiguo'}
      </button>

      {error ? <div className="admin-alert admin-alert--danger mt-4">{error}</div> : null}

      {result ? (
        <div className="admin-alert admin-alert--success mt-4">
          <p className="font-extrabold">Traducción completada</p>
          <ul className="mt-2 space-y-1 text-sm">
            {result.results.map((entry) => (
              <li key={entry.table}>
                {entry.label}: {entry.updated} actualizado{entry.updated === 1 ? '' : 's'}
                {entry.skipped ? `, ${entry.skipped} sin cambios` : ''}
                {entry.errors ? `, ${entry.errors} con errores` : ''}
              </li>
            ))}
          </ul>
          {result.hasMore ? (
            <p className="mt-2 text-sm">Quedan comentarios pendientes por traducir — pulsa el botón de nuevo para continuar.</p>
          ) : null}
        </div>
      ) : null}

      <AdminConfirmDialog
        open={confirmOpen}
        onClose={() => (running ? undefined : setConfirmOpen(false))}
        onConfirm={run}
        loading={running}
        titleId="translate-all-site-title"
        title="Reparar traducciones antiguas"
        tone="primary"
        confirmLabel="Traducir"
        message={<p>Se completará el contenido antiguo que todavía no tenga versión en español o inglés. Las traducciones existentes no se sobrescribirán.</p>}
      />
    </section>
  );
}
