import { Check, Eye, EyeOff, Loader2, Pencil, Plus, Trash2, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import {
  deletePackage,
  disableTourForBoat,
  enableTourForBoat,
  loadBoatToursPackages,
  packageSlug,
  savePackageForBoatTour,
  type AdminPackageRow,
  type AdminTourOption,
  type BoatToursPackagesData,
  type PackageInput,
} from '../../services/adminBoatToursService';
import AdminConfirmDialog from './AdminConfirmDialog';
import { AdminBadge } from './AdminPrimitives';
import { friendlyDeleteError } from '../../utils/adminErrors';
import { translateTextsToSpanish, TranslationError } from '../../services/translationService';
import { cleanList, editableList, editableText, textColumns, textsToTranslate, type BilingualColumns } from '../../utils/bilingualContent';
import { formatTime, money } from '../../utils/format';
import { parseMealOptions } from '../../utils/packageSettings';
import { useQueryClient } from '@tanstack/react-query';

interface Props {
  boatId: string;
  boatName: string;
  boatMaxGuests: number;
  /** Deep link (?tourId=): scroll to and briefly highlight this tour's card. */
  focusTourId?: string;
  /** Deep link (?packageId=, from Resumen de paquetes): scroll to and briefly highlight this package row. */
  focusPackageId?: string;
}

const NAME_COLUMNS: BilingualColumns = { legacy: 'name', en: 'name_en', es: 'name_es' };
const DESCRIPTION_COLUMNS: BilingualColumns = { legacy: 'description', en: 'description_en', es: 'description_es' };

interface DraftPackage {
  id: string;
  tourId: string;
  name: string;
  /** English text as loaded (what the form started with), to translate only what changes. */
  savedName: string;
  savedDescription: string;
  packageType: string;
  durationHours: string;
  basePrice: string;
  includedGuests: string;
  maxGuests: string;
  extraGuestPrice: string;
  description: string;
  departureTimes: string[];
  inheritTimes: boolean;
  // The admin only ever sees/edits `en` (English is the source). `es` is what is stored (kept as loaded until
  // the English changes, then regenerated by DeepL on save); `savedEn` is the English as loaded (null = new
  // meal), used to translate only what is new or changed.
  mealOptions: Array<{ es: string; en: string; savedEn: string | null }>;
  packageIncluded: string;
  /** package_included as loaded (null = inherits the tour's list, [] = explicitly none); to detect changes. */
  savedIncluded: string[] | null;
  overrideIncluded: boolean;
  customQuote: boolean;
  active: boolean;
  sortOrder: number;
  isNew: boolean;
}

type FieldErrors = Partial<Record<string, string>>;

function rowToDraft(row: AdminPackageRow, tourId: string, defaultTimes: string[]): DraftPackage {
  return {
    id: row.id,
    tourId,
    name: editableText(row, NAME_COLUMNS),
    savedName: editableText(row, NAME_COLUMNS),
    savedDescription: editableText(row, DESCRIPTION_COLUMNS),
    packageType: row.package_type,
    durationHours: row.duration_minutes == null ? '' : String(row.duration_minutes / 60),
    basePrice: String(row.base_price),
    includedGuests: String(row.included_guests),
    maxGuests: String(row.max_guests),
    extraGuestPrice: String(row.extra_guest_price),
    description: editableText(row, DESCRIPTION_COLUMNS),
    departureTimes: row.departure_times ?? defaultTimes,
    inheritTimes: row.departure_times == null,
    mealOptions: parseMealOptions(row.meal_options).map((meal) => ({ ...meal, savedEn: meal.en })),
    // NULL inherits the tour's list; otherwise the package's own list, shown in English.
    packageIncluded: (row.package_included === null ? [] : editableList(row, { legacy: 'package_included', en: 'package_included_en', es: 'package_included_es' })).join('\n'),
    savedIncluded: row.package_included === null ? null : editableList(row, { legacy: 'package_included', en: 'package_included_en', es: 'package_included_es' }),
    overrideIncluded: row.package_included != null,
    customQuote: row.custom_quote,
    active: row.active,
    sortOrder: row.sort_order,
    isNew: false,
  };
}

function newDraft(tourId: string, boatMaxGuests: number, sortOrder: number, defaultTimes: string[]): DraftPackage {
  return {
    id: `package-${crypto.randomUUID().slice(0, 8)}`,
    tourId,
    name: '',
    savedName: '',
    savedDescription: '',
    packageType: '',
    durationHours: '',
    basePrice: '',
    includedGuests: '1',
    maxGuests: String(boatMaxGuests),
    extraGuestPrice: '0',
    description: '',
    departureTimes: defaultTimes,
    inheritTimes: false,
    mealOptions: [],
    packageIncluded: '',
    savedIncluded: null,
    overrideIncluded: false,
    customQuote: false,
    active: true,
    sortOrder,
    isNew: true,
  };
}

function validateDraft(draft: DraftPackage, boatMaxGuests: number): FieldErrors {
  const errors: FieldErrors = {};
  const key = `pkg-${draft.id}`;
  if (!draft.name.trim()) errors[`${key}-name`] = 'El nombre es obligatorio.';
  if (draft.durationHours.trim() && (!Number.isFinite(Number(draft.durationHours)) || Math.round(Number(draft.durationHours) * 60) < 1)) {
    errors[`${key}-duration`] = 'Indica una duración válida de al menos un minuto o deja el campo vacío.';
  }
  if (!draft.basePrice.trim() || !Number.isFinite(Number(draft.basePrice)) || Number(draft.basePrice) < 0) {
    errors[`${key}-price`] = 'Ingresa un precio válido.';
  }
  const includedGuests = Number(draft.includedGuests);
  const extraGuestPrice = Number(draft.extraGuestPrice);
  if (!Number.isFinite(includedGuests) || includedGuests < 1) {
    errors[`${key}-included`] = 'Debe incluir al menos una persona.';
  }
  if (includedGuests > boatMaxGuests) {
    errors[`${key}-included`] = `El bote admite máximo ${boatMaxGuests} personas.`;
  }
  if (!Number.isFinite(extraGuestPrice) || extraGuestPrice < 0) {
    errors[`${key}-extra`] = 'El extra no puede ser negativo.';
  }
  if (!draft.inheritTimes && (draft.departureTimes.length > 48 || draft.departureTimes.some((time) => !/^([01]\d|2[0-3]):[0-5]\d$/.test(time)))) errors[`${key}-times`] = 'Revisa los horarios (máximo 48).';
  if (draft.mealOptions.length > 30 || draft.mealOptions.some((meal) => !meal.en.trim() || meal.en.trim().length > 120)) errors[`${key}-meals`] = 'Cada comida necesita un nombre (máximo 120 caracteres).';
  const included = draft.packageIncluded.split('\n').map((item) => item.trim()).filter(Boolean);
  if (draft.overrideIncluded && (included.length > 50 || included.some((item) => item.length > 300))) errors[`${key}-contents`] = 'Máximo 50 elementos de 300 caracteres.';
  return errors;
}

const includedItems = (draft: DraftPackage): string[] | null => (draft.overrideIncluded ? cleanList(draft.packageIncluded.split('\n')) : null);
const sameIncluded = (a: string[] | null, b: string[] | null) => (a === null || b === null ? a === b : a.length === b.length && a.every((item, index) => item === b[index]));

interface ResolvedTranslations {
  /** name_en/name_es and description_en/description_es for whatever changed ({} when nothing did). */
  bilingual: Record<string, unknown>;
  mealOptions: Array<{ es: string; en: string }>;
  /** undefined = "Incluye" did not change, leave package_included_es/_en alone. */
  includedEs?: string[] | null;
  includedEn?: string[] | null;
}

// Everything the admin writes here is ENGLISH; DeepL produces the Spanish (EN -> ES) when Guardar paquete is
// pressed. Name, description, "Incluye" and meals that are new or changed are translated in ONE batched
// request and only after that is anything written: if DeepL fails this throws, nothing is saved (not even the
// price), the stored EN/ES stay as they were and the editor keeps the text for a retry. What did not change is
// never sent to DeepL and its stored copies are not touched.
async function resolveTranslations(draft: DraftPackage): Promise<ResolvedTranslations> {
  const name = draft.name.trim();
  const description = draft.description.trim();
  const items = includedItems(draft);
  const includedChanged = !sameIncluded(items, draft.savedIncluded);
  const needsSpanish = (meal: DraftPackage['mealOptions'][number]) => meal.savedEn === null || meal.en.trim() !== meal.savedEn.trim() || !meal.es.trim();
  const texts = [
    ...textsToTranslate(name, draft.savedName),
    ...textsToTranslate(description, draft.savedDescription),
    ...(includedChanged && items ? items : []),
    ...draft.mealOptions.filter(needsSpanish).map((meal) => meal.en.trim()),
  ];
  const spanish = await translateTextsToSpanish(texts);

  const mealOptions = draft.mealOptions.map((meal) => {
    const en = meal.en.trim();
    const es = needsSpanish(meal) ? spanish.get(en) ?? '' : meal.es.trim();
    if (!es) throw new TranslationError();
    if (es.length > 120) throw new TranslationError(`La traducción al español de "${en}" supera 120 caracteres. Acorta el nombre de la comida.`);
    return { es, en };
  });
  const bilingual = {
    ...textColumns(name, draft.savedName, NAME_COLUMNS, spanish),
    ...textColumns(description, draft.savedDescription, DESCRIPTION_COLUMNS, spanish),
  };
  if (!includedChanged) return { bilingual, mealOptions };
  // Back to inheriting the tour's list -> clear the package copies so the tour's own ES/EN lists show;
  // an explicitly empty list stays empty in both languages (nothing to translate).
  if (!items) return { bilingual, mealOptions, includedEs: null, includedEn: null };
  const includedEs = items.map((item) => spanish.get(item) ?? '');
  if (includedEs.some((item) => !item)) throw new TranslationError();
  const tooLong = includedEs.findIndex((item) => item.length > 300);
  if (tooLong >= 0) throw new TranslationError(`La traducción al español de "${items[tooLong]}" supera 300 caracteres. Acorta el elemento.`);
  return { bilingual, mealOptions, includedEs, includedEn: items };
}

interface PackageDraftEditorProps {
  draft: DraftPackage;
  boatName: string;
  tourTitle: string;
  fieldErrors: FieldErrors;
  busy: boolean;
  boatMaxGuests: number;
  defaultTimes: string[];
  onChange: (changes: Partial<DraftPackage>) => void;
  onCancel: () => void;
  onSave: () => void;
  onDelete: () => void;
}

// Sections, not cards: each block has a small title and a divider. Advanced controls (custom hours,
// custom "incluye", meals) only appear when they are needed; the data written on save is unchanged.
function PackageDraftEditor({ draft, boatName, tourTitle, fieldErrors, busy, boatMaxGuests, defaultTimes, onChange, onCancel, onSave, onDelete }: PackageDraftEditorProps) {
  const key = `pkg-${draft.id}`;
  const [newTime, setNewTime] = useState('');
  const [confirmDeleteOpen, setConfirmDeleteOpen] = useState(false);
  const timeChoices = Array.from(new Set([...defaultTimes, ...draft.departureTimes])).sort();
  const fieldError = (name: string) => (fieldErrors[`${key}-${name}`] ? <span className="admin-field-error">{fieldErrors[`${key}-${name}`]}</span> : null);
  return (
    <div className="admin-package-compact-editor" role="group" aria-label={draft.isNew ? 'Nuevo paquete' : `Editar ${draft.name || 'paquete'}`}>
      <header className="admin-package-editor__head">
        <p className="admin-package-context" aria-label="Ubicación del paquete">{boatName || 'Bote'} / {tourTitle}</p>
        <h3>{draft.isNew ? 'Nuevo paquete' : `Editar ${draft.name || 'paquete'}`}</h3>
        <p className="admin-field-help">Escribe los textos del paquete en inglés: el español se genera al guardar.</p>
      </header>

      <section className="admin-package-section" aria-labelledby={`${key}-s-info`}>
        <h4 id={`${key}-s-info`}>Información del paquete</h4>
        <div className="admin-package-grid">
          <label className="admin-field">
            <span className="admin-field__label">Nombre</span>
            <input
              className="admin-input"
              value={draft.name}
              onChange={(event) => onChange({ name: event.target.value, packageType: packageSlug(event.target.value) })}
            />
            {fieldError('name')}
          </label>
          <label className="admin-field">
            <span className="admin-field__label">Duración (horas, opcional)</span>
            <input
              className="admin-input"
              type="text"
              inputMode="decimal"
              placeholder="Ej.: 2,5 o 4"
              value={draft.durationHours}
              onChange={(event) => onChange({ durationHours: event.target.value.replace(',', '.') })}
            />
            <span className="admin-field-help">Vacío si la duración se acuerda con el cliente.</span>
            {fieldError('duration')}
          </label>
        </div>
        <label className="admin-field">
          <span className="admin-field__label">Descripción</span>
          <textarea
            className="admin-input admin-textarea-list"
            rows={3}
            value={draft.description}
            onChange={(event) => onChange({ description: event.target.value })}
          />
        </label>
      </section>

      <section className="admin-package-section" aria-labelledby={`${key}-s-price`}>
        <h4 id={`${key}-s-price`}>Precio y capacidad</h4>
        <div className="admin-package-grid">
          <label className="admin-field">
            <span className="admin-field__label">Precio base (USD)</span>
            <input
              className="admin-input admin-input--manual-number"
              type="text"
              inputMode="decimal"
              min={0}
              step="any"
              value={draft.basePrice}
              onChange={(event) => onChange({ basePrice: event.target.value })}
            />
            {fieldError('price')}
          </label>
          <label className="admin-field">
            <span className="admin-field__label">Extra por persona adicional (USD)</span>
            <input
              className="admin-input"
              type="text"
              inputMode="decimal"
              min={0}
              value={draft.extraGuestPrice}
              onChange={(event) => onChange({ extraGuestPrice: event.target.value })}
            />
            {fieldError('extra')}
          </label>
          <label className="admin-field">
            <span className="admin-field__label">Personas incluidas</span>
            <input
              className="admin-input"
              type="number"
              min={1}
              max={boatMaxGuests}
              value={draft.includedGuests}
              onChange={(event) => onChange({ includedGuests: event.target.value })}
            />
            {fieldError('included')}
          </label>
          <label className="admin-field">
            <span className="admin-field__label">Máximo del paquete</span>
            <input
              className="admin-input"
              type="number"
              min={1}
              max={boatMaxGuests}
              value={draft.maxGuests}
              onChange={(event) => onChange({ maxGuests: event.target.value })}
            />
            <span className="admin-field-help">Techo físico del bote: {boatMaxGuests}.</span>
          </label>
        </div>
        <label className="admin-package-check">
          <input type="checkbox" checked={draft.customQuote} onChange={(event) => onChange({ customQuote: event.target.checked })} />
          <span>Cotización personalizada (sin precio automático)</span>
        </label>
      </section>

      <section className="admin-package-section" aria-labelledby={`${key}-s-times`}>
        <h4 id={`${key}-s-times`}>Horarios</h4>
        <fieldset className="admin-package-fieldset" disabled={busy}>
          <legend className="admin-visually-hidden">Horas de salida de este paquete</legend>
          <label className="admin-package-check">
            <input type="checkbox" checked={draft.inheritTimes} onChange={(event) => onChange({ inheritTimes: event.target.checked })} />
            <span>Usar los horarios generales</span>
          </label>
          {draft.inheritTimes ? (
            <span className="admin-field-help">Se ofrecen todos los horarios generales de salida.</span>
          ) : (
            <>
              <div className="admin-time-chips">
                {timeChoices.map((time) => (
                  <label key={time} className="admin-time-chip">
                    <input type="checkbox" checked={draft.departureTimes.includes(time)} onChange={(event) => onChange({ departureTimes: event.target.checked ? [...draft.departureTimes, time] : draft.departureTimes.filter((item) => item !== time) })} />
                    {formatTime(time)}
                  </label>
                ))}
              </div>
              <div className="admin-package-inline-add">
                <label className="admin-field">
                  <span className="admin-field__label">Agregar hora de salida</span>
                  <input className="admin-input" type="time" step="60" value={newTime} onChange={(event) => setNewTime(event.target.value)} />
                </label>
                <button className="admin-btn admin-btn--secondary" type="button" disabled={!newTime || draft.departureTimes.includes(newTime)} onClick={() => { onChange({ departureTimes: [...draft.departureTimes, newTime] }); setNewTime(''); }}><Plus size={15} /> Agregar hora</button>
              </div>
              <span className="admin-field-help">Sin ninguna hora marcada, el paquete no se puede reservar.</span>
            </>
          )}
          {fieldErrors[`${key}-times`] ? <span className="admin-field-error" role="alert">{fieldErrors[`${key}-times`]}</span> : null}
        </fieldset>
      </section>

      <section className="admin-package-section" aria-labelledby={`${key}-s-includes`}>
        <h4 id={`${key}-s-includes`}>Incluye</h4>
        <fieldset className="admin-package-fieldset" disabled={busy}>
          <legend className="admin-visually-hidden">Qué incluye este paquete</legend>
          <label className="admin-package-check">
            <input type="checkbox" checked={draft.overrideIncluded} onChange={(event) => onChange({ overrideIncluded: event.target.checked })} />
            <span>Personalizar lo incluido</span>
          </label>
          {draft.overrideIncluded ? (
            <label className="admin-field">
              <span className="admin-field__label">Elementos incluidos, uno por línea</span>
              <textarea className="admin-input admin-textarea-list" rows={4} placeholder={'Fishing equipment\nDrinks\nSnacks'} value={draft.packageIncluded} onChange={(event) => onChange({ packageIncluded: event.target.value })} />
              <span className="admin-field-help">Escríbelos en inglés: el español se genera al guardar.</span>
            </label>
          ) : (
            <span className="admin-field-help">Se usa la lista de lo incluido en el tour.</span>
          )}
          {fieldErrors[`${key}-contents`] ? <span className="admin-field-error" role="alert">{fieldErrors[`${key}-contents`]}</span> : null}
        </fieldset>
        <fieldset className="admin-package-fieldset" disabled={busy}>
          <legend className="admin-package-subtitle">Comidas para elegir <span className="admin-muted">(opcional)</span></legend>
          <span className="admin-field-help">{draft.mealOptions.length === 0 ? 'Sin comidas, el cliente no verá selector de comida. ' : ''}Escríbelas en inglés: el español se genera al guardar.</span>
          {draft.mealOptions.map((meal, index) => (
            <div className="admin-package-meal" key={index}>
              <label className="admin-field"><span className="admin-field__label">Comida {index + 1}</span><input className="admin-input" maxLength={120} placeholder="e.g. Fish casado" value={meal.en} onChange={(event) => onChange({ mealOptions: draft.mealOptions.map((item, position) => position === index ? { ...item, en: event.target.value } : item) })} /></label>
              <button className="admin-icon-btn" type="button" aria-label={`Eliminar comida ${index + 1}`} title="Eliminar comida" onClick={() => onChange({ mealOptions: draft.mealOptions.filter((_, position) => position !== index) })}><Trash2 size={15} /></button>
            </div>
          ))}
          <div>
            <button className="admin-btn admin-btn--secondary" type="button" disabled={draft.mealOptions.length >= 30} onClick={() => onChange({ mealOptions: [...draft.mealOptions, { es: '', en: '', savedEn: null }] })}><Plus size={15} /> Agregar comida</button>
          </div>
          {fieldErrors[`${key}-meals`] ? <span className="admin-field-error" role="alert">{fieldErrors[`${key}-meals`]}</span> : null}
        </fieldset>
      </section>

      <section className="admin-package-section admin-package-visibility" aria-labelledby={`${key}-s-visibility`}>
        <h4 id={`${key}-s-visibility`}>Visibilidad</h4>
        <div className="admin-package-visibility__row">
          <div>
            <AdminBadge value={draft.active ? true : 'Inactivo'} label={draft.active ? 'Activo' : 'Inactivo'} />
            <span className="admin-muted">{draft.active ? 'Visible y reservable.' : 'Oculto y no reservable.'}</span>
          </div>
          <button
            className={`admin-btn ${draft.active ? 'admin-btn--secondary' : ''}`}
            type="button"
            onClick={() => onChange({ active: !draft.active })}
          >
            {draft.active ? <EyeOff size={15} /> : <Eye size={15} />}
            {draft.active ? 'Desactivar paquete' : 'Activar paquete'}
          </button>
        </div>
      </section>

      <footer className="admin-package-editor__footer">
        {!draft.isNew ? (
          <button className="admin-btn admin-btn--ghost admin-package-editor__delete" type="button" disabled={busy} onClick={() => setConfirmDeleteOpen(true)}>
            <Trash2 size={15} /> Eliminar paquete
          </button>
        ) : <span />}
        <div className="admin-package-editor__actions">
          <button className="admin-btn admin-btn--secondary" type="button" onClick={onCancel}>Cancelar</button>
          <button className="admin-btn" type="button" disabled={busy} onClick={onSave}>
            {busy ? <Loader2 className="animate-spin" size={15} /> : <Check size={15} />} Guardar paquete
          </button>
        </div>
      </footer>

      <AdminConfirmDialog
        open={confirmDeleteOpen}
        onClose={() => setConfirmDeleteOpen(false)}
        onConfirm={() => { setConfirmDeleteOpen(false); onDelete(); }}
        titleId="confirm-package-delete-title"
        title="Eliminar paquete"
        loading={busy}
        cancelLabel="Volver"
        confirmLabel="Sí, eliminar paquete"
        message={`¿Eliminar "${draft.name || 'este paquete'}"? Esta acción no se puede deshacer.`}
      />
    </div>
  );
}

export default function BoatToursPackagesEditor({ boatId, boatName, boatMaxGuests, focusTourId, focusPackageId }: Props) {
  const queryClient = useQueryClient();
  const [data, setData] = useState<BoatToursPackagesData | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [draft, setDraft] = useState<DraftPackage | null>(null);
  const [fieldErrors, setFieldErrors] = useState<FieldErrors>({});
  const [confirmRemove, setConfirmRemove] = useState<AdminTourOption | null>(null);
  const [availableQuery, setAvailableQuery] = useState('');
  const [highlightTourId, setHighlightTourId] = useState<string | null>(null);
  const focusedRef = useRef<string | null>(null);
  const [highlightPackageId, setHighlightPackageId] = useState<string | null>(null);
  const focusedPackageRef = useRef<string | null>(null);

  const reload = useCallback(async () => {
    setLoading(true);
    try {
      setData(await loadBoatToursPackages(boatId));
      setError('');
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : 'No se pudo cargar el catálogo de tours.');
    } finally {
      setLoading(false);
    }
  }, [boatId]);

  useEffect(() => {
    void reload();
  }, [reload]);

  const linkByTour = useMemo(() => {
    const map = new Map<string, BoatToursPackagesData['links'][number]>();
    for (const link of data?.links ?? []) map.set(link.tour_id, link);
    return map;
  }, [data]);

  const catalogTours = useMemo(
    () => Array.from(new Map((data?.tours ?? []).map((tour) => [tour.id, tour])).values()),
    [data],
  );

  const packagesByTour = useMemo(() => {
    const map = new Map<string, AdminPackageRow[]>();
    const linkTour = new Map((data?.links ?? []).map((link) => [link.id, link.tour_id]));
    for (const row of data?.packages ?? []) {
      const tourId = linkTour.get(row.boat_tour_id);
      if (!tourId) continue;
      const list = map.get(tourId) ?? [];
      list.push(row);
      map.set(tourId, list);
    }
    for (const list of map.values()) list.sort((a, b) => a.sort_order - b.sort_order);
    return map;
  }, [data]);

  // "En este bote" = tours the boat currently offers (boat_tours.active). "Quitar" only switches that
  // off (see disableTourForBoat), so a removed tour goes back to "Disponibles para agregar" with its
  // packages kept, and adding it again (enableTourForBoat) brings them back.
  const assignedTours = useMemo(
    () => catalogTours.filter((tour) => linkByTour.get(tour.id)?.active === true),
    [catalogTours, linkByTour],
  );
  const availableTours = useMemo(
    () => catalogTours.filter((tour) => linkByTour.get(tour.id)?.active !== true),
    [catalogTours, linkByTour],
  );

  async function run(action: () => Promise<void>, okMessage?: string) {
    setBusy(true);
    setError('');
    setNotice('');
    try {
      await action();
      if (okMessage) setNotice(okMessage);
      await reload();
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : 'La operación no se pudo completar.');
    } finally {
      setBusy(false);
    }
  }

  function closeEditor() {
    setEditingId(null);
    setDraft(null);
    setFieldErrors({});
  }

  const defaultTimes = Array.from(new Set((data?.timeSlots ?? []).map((slot) => slot.starts_at.slice(0, 5)))).sort();

  function startEditing(row: AdminPackageRow, tourId: string) {
    setDraft(rowToDraft(row, tourId, defaultTimes));
    setEditingId(row.id);
    setFieldErrors({});
  }

  function startCreating(tour: AdminTourOption) {
    // max(sort_order)+1, not count+1: after a package is deleted the remaining values have
    // a gap, and count+1 would collide with one that still exists.
    const nextOrder = (packagesByTour.get(tour.id) ?? []).reduce((max, item) => Math.max(max, item.sort_order), 0) + 1;
    const next = newDraft(tour.id, boatMaxGuests, nextOrder, defaultTimes);
    setDraft(next);
    setEditingId(next.id);
    setFieldErrors({});
  }

  function updateDraft(changes: Partial<DraftPackage>) {
    setDraft((current) => (current ? { ...current, ...changes } : current));
  }

  async function persistDraft() {
    if (!draft) return;
    const errors = validateDraft(draft, boatMaxGuests);
    setFieldErrors(errors);
    if (Object.keys(errors).length) return;

    const input: PackageInput = {
      id: draft.id,
      name: draft.name,
      packageType: draft.packageType || packageSlug(draft.name),
      durationMinutes: draft.durationHours.trim() ? Math.round(Number(draft.durationHours) * 60) : null,
      basePrice: Number(draft.basePrice),
      includedGuests: Number(draft.includedGuests),
      maxGuests: Number(draft.maxGuests),
      extraGuestPrice: Number(draft.extraGuestPrice),
      description: draft.description.trim() || null,
      departureTimes: draft.inheritTimes ? null : draft.departureTimes,
      mealOptions: [],
      packageIncluded: includedItems(draft),
      customQuote: draft.customQuote,
      active: draft.active,
      sortOrder: draft.sortOrder,
    };
    await run(async () => {
      // Translation happens only here, on the explicit save, and before any write.
      const resolved = await resolveTranslations(draft);
      input.mealOptions = resolved.mealOptions;
      input.bilingual = resolved.bilingual;
      input.packageIncludedEs = resolved.includedEs;
      input.packageIncludedEn = resolved.includedEn;
      await savePackageForBoatTour(boatId, draft.tourId, input, boatMaxGuests);
      await Promise.all([queryClient.invalidateQueries({ queryKey: ['boatTours'] }), queryClient.invalidateQueries({ queryKey: ['availability'] })]);
      closeEditor();
    }, 'Paquete guardado.');
  }

  async function removeDraft() {
    if (!draft) return;
    await run(async () => {
      try {
        await deletePackage(draft.id);
      } catch (caught) {
        throw new Error(friendlyDeleteError({ message: caught instanceof Error ? caught.message : String(caught) }, 'este paquete'));
      }
      closeEditor();
    }, 'Paquete eliminado.');
  }

  useEffect(() => {
    if (!focusTourId || loading || focusedRef.current === focusTourId || !linkByTour.has(focusTourId)) return;
    focusedRef.current = focusTourId;
    // An offered tour has its own card; one that is linked but switched off waits in "Disponibles".
    window.requestAnimationFrame(() => (document.getElementById(`boat-tour-${focusTourId}`) ?? document.getElementById(`boat-tour-available-${focusTourId}`))?.scrollIntoView?.({ block: 'center' }));
    setHighlightTourId(focusTourId);
    window.setTimeout(() => setHighlightTourId(null), 3500);
  }, [focusTourId, loading, linkByTour]);

  useEffect(() => {
    if (!focusPackageId || loading || focusedPackageRef.current === focusPackageId || !data?.packages.some((row) => row.id === focusPackageId)) return;
    focusedPackageRef.current = focusPackageId;
    window.requestAnimationFrame(() => document.getElementById(`boat-package-${focusPackageId}`)?.scrollIntoView?.({ block: 'center' }));
    setHighlightPackageId(focusPackageId);
    window.setTimeout(() => setHighlightPackageId(null), 4500);
  }, [focusPackageId, loading, data]);

  if (loading) return <p className="admin-muted">Cargando tours y paquetes...</p>;

  const activePackageCount = assignedTours.reduce((sum, tour) => sum + (packagesByTour.get(tour.id) ?? []).filter((row) => row.active).length, 0);
  const query = availableQuery.trim().toLowerCase();
  const visibleAvailable = query ? availableTours.filter((tour) => tour.title.toLowerCase().includes(query)) : availableTours;
  const boatLabel = boatName || 'este bote';
  const packageCount = (tourId: string) => (packagesByTour.get(tourId) ?? []).length;

  return (
    <div className="admin-boat-tours-editor">
      {error ? <div className="admin-alert admin-alert--danger" role="alert">{error}</div> : null}
      {notice ? <div className="admin-alert admin-alert--success">{notice}</div> : null}

      <header className="admin-boat-tours__head">
        <div>
          <h3 className="admin-boat-tours__title">Tours y paquetes</h3>
          <p className="admin-muted">Selecciona los tours disponibles en este bote y configura sus paquetes.</p>
        </div>
        <ul className="admin-boat-tours__stats" aria-label="Resumen de este bote">
          <li><strong>{assignedTours.length}</strong> {assignedTours.length === 1 ? 'tour ofrecido' : 'tours ofrecidos'}</li>
          <li><strong>{activePackageCount}</strong> {activePackageCount === 1 ? 'paquete activo' : 'paquetes activos'}</li>
        </ul>
      </header>

      <div className={`admin-boat-tours__layout${draft ? ' admin-boat-tours__layout--editing' : ''}`}>
      <section className="admin-boat-tours__section" aria-label={`Tours de ${boatLabel}`}>
        <h4 className="admin-boat-tours__section-title">En {boatLabel} <span className="admin-boat-tours__count">{assignedTours.length}</span></h4>
        {assignedTours.length === 0 ? (
          <p className="admin-boat-tours__empty">
            {catalogTours.length === 0
              ? 'No hay tours en el catálogo. Créalos primero en la sección Tours.'
              : `${boatName || 'Este bote'} todavía no ofrece ningún tour. Elige uno de los tours disponibles para empezar.`}
          </p>
        ) : null}
      {assignedTours.map((tour) => {
        const list = packagesByTour.get(tour.id) ?? [];
        const prices = list.filter((row) => row.active && !row.custom_quote).map((row) => Number(row.base_price));
        const fromPrice = prices.length ? Math.min(...prices) : null;
        const creatingHere = Boolean(editingId && draft?.isNew && draft.tourId === tour.id);
        return (
          <section
            key={tour.id}
            id={`boat-tour-${tour.id}`}
            className={`admin-boat-tour-card${highlightTourId === tour.id ? ' admin-boat-tour-card--highlight' : ''}`}
            aria-label={`${tour.title} en ${boatLabel}`}
          >
            <header className="admin-boat-tour-card__head">
              <div>
                <h4>{tour.title}</h4>
                <p className="admin-muted">{list.length === 0 ? 'Sin paquetes todavía' : `${list.length} ${list.length === 1 ? 'paquete' : 'paquetes'}${fromPrice !== null ? ` · Desde ${money(fromPrice)}` : ''}`}</p>
              </div>
              <div className="admin-boat-tour-card__head-actions">
                <AdminBadge value={true} label="Activo" />
                <button
                  className="admin-icon-btn admin-boat-tour-card__remove"
                  type="button"
                  disabled={busy}
                  title="Quitar este tour del bote"
                  aria-label={`Quitar ${tour.title} del bote`}
                  onClick={() => setConfirmRemove(tour)}
                >
                  <X size={16} />
                </button>
              </div>
            </header>

            {list.length === 0 && !creatingHere ? (
              <p className="admin-boat-tour-card__empty">Este tour aún no tiene paquetes. Agrega el primero para poder reservarlo en {boatLabel}.</p>
            ) : null}
            <ul className="admin-boat-package-list">
              {list.map((row) => (
                <li key={row.id}>
                  <div id={`boat-package-${row.id}`} className={`admin-boat-package-row${highlightPackageId === row.id ? ' admin-boat-package-row--highlight' : ''}`}>
                    <div className="admin-boat-package-row__main">
                      <strong>
                        {row.name || 'Paquete sin nombre'}
                        {!row.active ? <span className="admin-muted"> · inactivo</span> : null}
                      </strong>
                      <span className="admin-muted">{row.included_guests} incluidos / {row.max_guests} máximo</span>
                    </div>
                    <span className="admin-boat-package-row__price">{row.custom_quote ? 'Cotizar' : money(Number(row.base_price))}</span>
                    <button
                      className="admin-action-btn"
                      type="button"
                      title="Editar paquete"
                      aria-label={`Editar ${row.name || 'paquete'}`}
                      onClick={() => (editingId === row.id ? closeEditor() : startEditing(row, tour.id))}
                    >
                      <Pencil size={14} /> Editar
                    </button>
                  </div>
                  {editingId === row.id && draft ? (
                    <PackageDraftEditor
                      draft={draft}
                      boatName={boatName}
                      tourTitle={tour.title}
                      fieldErrors={fieldErrors}
                      busy={busy}
                      boatMaxGuests={boatMaxGuests}
                      defaultTimes={defaultTimes}
                      onChange={updateDraft}
                      onCancel={closeEditor}
                      onSave={() => void persistDraft()}
                      onDelete={() => void removeDraft()}
                    />
                  ) : null}
                </li>
              ))}
              {creatingHere && draft ? (
                <li>
                  <PackageDraftEditor
                    draft={draft}
                    boatName={boatName}
                    tourTitle={tour.title}
                    fieldErrors={fieldErrors}
                    busy={busy}
                    boatMaxGuests={boatMaxGuests}
                    defaultTimes={defaultTimes}
                    onChange={updateDraft}
                    onCancel={closeEditor}
                    onSave={() => void persistDraft()}
                    onDelete={() => void removeDraft()}
                  />
                </li>
              ) : null}
            </ul>

            {!creatingHere ? (
              <footer className="admin-boat-tour-card__actions">
                <button className="admin-btn admin-btn--secondary" type="button" disabled={busy} onClick={() => startCreating(tour)}>
                  <Plus size={15} /> Agregar paquete
                </button>
              </footer>
            ) : null}
          </section>
        );
      })}

      </section>

      <section className="admin-boat-tours__section admin-boat-tours__available" role="group" aria-label="Tours que se pueden agregar">
        <h4 className="admin-boat-tours__section-title">Disponibles para agregar <span className="admin-boat-tours__count">{availableTours.length}</span></h4>
        {availableTours.length ? (
          <>
            {availableTours.length > 6 ? (
              <input
                className="admin-input admin-boat-tours__search"
                type="search"
                aria-label="Buscar tour disponible"
                placeholder="Buscar tour"
                value={availableQuery}
                onChange={(event) => setAvailableQuery(event.target.value)}
              />
            ) : null}
            <ul className="admin-boat-tours__available-list">
              {visibleAvailable.map((tour) => (
                <li key={tour.id} id={`boat-tour-available-${tour.id}`} className={highlightTourId === tour.id ? 'admin-boat-tours__available-item--highlight' : undefined}>
                  <span className="admin-boat-tours__available-name">
                    {tour.title}
                    {tour.publication_status === 'draft' ? <small className="admin-muted"> · borrador</small> : null}
                    {packageCount(tour.id) > 0 ? <small className="admin-muted"> · {packageCount(tour.id)} {packageCount(tour.id) === 1 ? 'paquete guardado' : 'paquetes guardados'}</small> : null}
                  </span>
                  <button
                    className="admin-btn admin-btn--secondary admin-btn--sm"
                    type="button"
                    disabled={busy}
                    aria-label={`Agregar al bote: ${tour.title}`}
                    onClick={() => void run(() => enableTourForBoat(boatId, tour.id, tour.sort_order), `${tour.title} agregado a ${boatLabel}.`)}
                  >
                    <Plus size={14} /> Agregar
                  </button>
                </li>
              ))}
              {visibleAvailable.length === 0 ? <li className="admin-muted">Ningún tour coincide con la búsqueda.</li> : null}
            </ul>
          </>
        ) : (
          <p className="admin-muted">Todos los tours ya están en {boatLabel}.</p>
        )}
      </section>
      </div>

      <AdminConfirmDialog
        open={Boolean(confirmRemove)}
        onClose={() => setConfirmRemove(null)}
        onConfirm={() => {
          const tour = confirmRemove;
          setConfirmRemove(null);
          if (tour) void run(() => disableTourForBoat(boatId, tour.id), `${tour.title} quitado de ${boatLabel}. Sus paquetes se conservan.`);
        }}
        titleId="confirm-tour-remove-title"
        title="Quitar tour del bote"
        tone="primary"
        cancelLabel="Volver"
        confirmLabel="Quitar tour"
        message={confirmRemove ? (
          <>
            <p>Este tour dejará de ofrecerse en este bote.</p>
            <p className="admin-muted">{confirmRemove.title} no se elimina del sistema ni de otros botes. Sus paquetes en {boatLabel} se conservan (inactivos) y puedes volver a agregarlo desde “Disponibles para agregar”.</p>
          </>
        ) : ''}
      />
    </div>
  );
}
