// Pure helpers for the Admin's "write English, DeepL generates Spanish" rule.
//
// Every translatable public field is stored as three columns: the legacy single field (`title`), its English
// copy (`title_en`, the canonical text the admin wrote) and its Spanish copy (`title_es`, generated by DeepL).
// The Admin form shows the English text (`_en`, else the legacy field) and, on an explicit save:
//   - text unchanged      -> nothing is translated and the stored `_en` / `_es` are not written;
//   - text new or changed -> the English is stored in `_en` and the DeepL Spanish in `_es`;
//   - text cleared        -> `_en` and `_es` are cleared together (a stale copy would keep showing publicly).
// The callers translate everything a save needs BEFORE writing anything (see translateTextsToSpanish), so a
// DeepL failure persists nothing.

export type BilingualRow = Record<string, unknown>;

/** Column names of one bilingual field. */
export interface BilingualColumns {
  legacy: string;
  en: string;
  es: string;
}

const clean = (value: unknown): string => (typeof value === 'string' ? value.trim() : '');

export const cleanList = (value: unknown): string[] =>
  Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string' && item.trim().length > 0).map((item) => item.trim()) : [];

/** The English text of a stored field: the `_en` copy when there is one, otherwise the legacy field. */
export function editableText(row: BilingualRow | null | undefined, columns: BilingualColumns): string {
  return clean(row?.[columns.en]) || clean(row?.[columns.legacy]);
}

/** The English list of a stored array field (`_en` copy, else legacy). */
export function editableList(row: BilingualRow | null | undefined, columns: BilingualColumns): string[] {
  const english = cleanList(row?.[columns.en]);
  return english.length > 0 ? english : cleanList(row?.[columns.legacy]);
}

export const sameList = (a: string[], b: string[]) => a.length === b.length && a.every((item, index) => item === b[index]);

/** Texts that must go to DeepL for a scalar field: [] unless the value is new or changed (and not empty). */
export function textsToTranslate(value: string, before: string): string[] {
  const text = value.trim();
  return text && text !== before.trim() ? [text] : [];
}

/** Texts for a list field: every item, but only when the list changed. */
export function listTextsToTranslate(items: string[], before: string[]): string[] {
  return items.length > 0 && !sameList(items, before) ? items : [];
}

/**
 * Columns to write for a scalar field: {} when unchanged; {en: null, es: null} when cleared; otherwise
 * {en: <English>, es: <Spanish>}. Throws if a needed translation is missing, so a save can never store
 * English without its Spanish.
 */
export function textColumns(value: string, before: string, columns: Pick<BilingualColumns, 'en' | 'es'>, spanish: Map<string, string>): BilingualRow {
  const text = value.trim();
  if (text === before.trim()) return {};
  if (!text) return { [columns.en]: null, [columns.es]: null };
  const translation = spanish.get(text);
  if (!translation) throw new Error(`Missing Spanish translation for "${text}"`);
  return { [columns.en]: text, [columns.es]: translation };
}

/** Same as textColumns for an array field (jsonb or text[]): {} unchanged, [] cleared, else parallel EN / ES arrays. */
export function listColumns(items: string[], before: string[], columns: Pick<BilingualColumns, 'en' | 'es'>, spanish: Map<string, string>): BilingualRow {
  if (sameList(items, before)) return {};
  if (items.length === 0) return { [columns.en]: [], [columns.es]: [] };
  const translated = items.map((item) => {
    const translation = spanish.get(item);
    if (!translation) throw new Error(`Missing Spanish translation for "${item}"`);
    return translation;
  });
  return { [columns.en]: items, [columns.es]: translated };
}
